"""add_region_column_to_daily_weather

Revision ID: 4c9978c514cd
Revises: cb98f757fcb4
Create Date: 2026-01-24 13:46:12.239798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9978c514cd'
down_revision: Union[str, Sequence[str], None] = 'cb98f757fcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_weather', sa.Column('region', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_daily_weather_region'), 'daily_weather', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_weather_region'), table_name='daily_weather')
    op.drop_column('daily_weather', 'region')
    # ### end Alembic commands ###
