"""revise daily_weather table

Revision ID: 4df63da93268
Revises: 4c9978c514cd
Create Date: 2026-01-26 15:18:24.767782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df63da93268'
down_revision: Union[str, Sequence[str], None] = '4c9978c514cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_weather', sa.Column('base_date', sa.String(length=8), nullable=False))
    op.add_column('daily_weather', sa.Column('base_time', sa.String(length=4), nullable=False))
    op.drop_constraint(op.f('uix_daily_weather'), 'daily_weather', type_='unique')
    op.create_unique_constraint('uix_daily_weather', 'daily_weather', ['base_date', 'nx', 'ny'])
    op.drop_column('daily_weather', 'date_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_weather', sa.Column('date_id', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.drop_constraint('uix_daily_weather', 'daily_weather', type_='unique')
    op.create_unique_constraint(op.f('uix_daily_weather'), 'daily_weather', ['date_id', 'nx', 'ny'], postgresql_nulls_not_distinct=False)
    op.drop_column('daily_weather', 'base_time')
    op.drop_column('daily_weather', 'base_date')
    # ### end Alembic commands ###
