"""Initial schema

Revision ID: 9e4180a97464
Revises: 
Create Date: 2026-01-22 22:49:27.559469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e4180a97464'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('closet_items', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('closet_items', 'thickness_level')
    op.drop_column('closet_items', 'color_primary')
    op.drop_column('closet_items', 'material')
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.add_column('closet_items', sa.Column('material', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('closet_items', sa.Column('color_primary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('closet_items', sa.Column('thickness_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('closet_items', 'features')
    # ### end Alembic commands ###
