"""extend_todays_pick_model

Revision ID: c6f1f41c8389
Revises: cb94e87dc718
Create Date: 2026-01-27 02:59:46.328457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f1f41c8389'
down_revision: Union[str, Sequence[str], None] = 'cb94e87dc718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todays_picks', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('todays_picks', sa.Column('reasoning', sa.String(), nullable=True))
    op.add_column('todays_picks', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('todays_picks', sa.Column('weather_snapshot', sa.JSON(), nullable=True))
    op.add_column('todays_picks', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_todays_picks_date'), 'todays_picks', ['date'], unique=False)
    op.create_index(op.f('ix_todays_picks_is_active'), 'todays_picks', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todays_picks_is_active'), table_name='todays_picks')
    op.drop_index(op.f('ix_todays_picks_date'), table_name='todays_picks')
    op.drop_column('todays_picks', 'is_active')
    op.drop_column('todays_picks', 'weather_snapshot')
    op.drop_column('todays_picks', 'score')
    op.drop_column('todays_picks', 'reasoning')
    op.drop_column('todays_picks', 'date')
    # ### end Alembic commands ###
