"""add_todays_pick_table

Revision ID: cb94e87dc718
Revises: 4df63da93268
Create Date: 2026-01-27 00:35:06.454811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cb94e87dc718"
down_revision: Union[str, Sequence[str], None] = "4df63da93268"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 기존 테이블 삭제 (데이터 타입 충돌 해결을 위해)
    op.drop_table("todays_picks")

    # 2. 새 스키마로 다시 생성
    op.create_table(
        "todays_picks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("top_item_id", sa.String(), nullable=True),
        sa.Column("bottom_item_id", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_todays_picks_id"), "todays_picks", ["id"], unique=False)
    op.create_foreign_key(None, "todays_picks", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todays_picks",
        sa.Column(
            "weather_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "todays_picks",
        sa.Column("top_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "todays_picks",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "todays_picks",
        sa.Column("reasoning", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "todays_picks",
        sa.Column(
            "date",
            sa.DATE(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "todays_picks",
        sa.Column("bottom_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("todays_picks_top_id_fkey"),
        "todays_picks",
        "closet_items",
        ["top_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("todays_picks_bottom_id_fkey"),
        "todays_picks",
        "closet_items",
        ["bottom_id"],
        ["id"],
    )
    op.alter_column(
        "todays_picks", "image_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "todays_picks",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("todays_picks", "created_at")
    op.drop_column("todays_picks", "prompt")
    op.drop_column("todays_picks", "bottom_item_id")
    op.drop_column("todays_picks", "top_item_id")
    # ### end Alembic commands ###
